Peals/Controllers/ActividadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Peals.Models;
using System.Data.SqlClient;
using System.Data.Objects;
using System.Data;

namespace Peals.Controllers
{
    public class ActividadController : Controller
    {
        private pealsEntities mDb = new pealsEntities();
        private RecursoController mRecursoController = new RecursoController();

        public ActionResult Index()
        {
            ViewBag.DefaultMessage = "No tiene ninguna actividad creada.";

            return View();
        }

        public ActionResult CrearActividad()
        {
            int id_docente = Utiles.Sesion.GetIdUsuarioLogeado(ControllerContext);
            List<criterio_evaluacion> criterios = mDb.criterio_evaluacion.Where(x => x.docente == id_docente).ToList<criterio_evaluacion>();
            ViewBag.Criterios = criterios;

            //List<senia> senias = mDb.senia.Where(x=> x.activo.Value).ToList<senia>();
            //ViewBag.Senias = senias;

            return View();
        }

        public ActionResult _Senias(String filtro = "")
        {
            List<senia> senias = mDb.senia.Where(x => x.activo.Value && x.clase.Contains(filtro)).OrderBy(x => x.clase).ToList<senia>();
            return PartialView(senias);
        }

        /// <summary>
        /// Guarda la actividad en la base de datos, subiendo también la nuevas imágenes.
        /// </summary>
        /// <param name="actividad">JSON de la actividad</param>
        /// <param name="criterio">Id del criterio de evaluacion</param>
        public ActionResult GuardarActividad(string actividad, string criterio, HttpPostedFileBase video)
        {
            int user_id = Utiles.Sesion.GetIdUsuarioLogeado(ControllerContext);

            dynamic json = Newtonsoft.Json.JsonConvert.DeserializeObject(actividad);
            actividad act = new actividad();
            act.nombre = json.nombre;
            act.descripcion = json.explicacion;

            if (video != null)
            {
                act.videoExplicacion = Utiles.Utils.GuardarArchivoEnDisco(video, ControllerContext);
            }

            act.docente = user_id;
            act.criterio = int.Parse(criterio);
            act.fecha_alta = System.DateTime.Now;
            act.estado = 1;
            mDb.actividad.AddObject(act);
            mDb.SaveChanges();

            Dictionary<int, int> recursosNuevos = new Dictionary<int, int>();

            for (int i = 0; i < json.ejercicios.Count; i++)
            {
                ejercicio ejer = new ejercicio();
                ejer.actividad = act.id;
                ejer.zoom = json.ejercicios[i].zoom;

                mDb.ejercicio.AddObject(ejer);

                mDb.SaveChanges();

                int id_recurso_correcto = -1;
                for (int j = 0; j < json.ejercicios[i].recursos.Count; j++)
                {
                    int type = json.ejercicios[i].recursos[j].type + 1;
                    int id_recurso = -1;
                    if (type == (int)TipoDeRecurso.Texto)
                    {
                        string text = json.ejercicios[i].recursos[j].text;
                        recurso recurso = new recurso()
                        {
                            nombre = "",
                            ruta = text,
                            tipo_recurso = type,
                            subido_por = user_id,
                            estado = 1
                        };

                        mDb.recurso.AddObject(recurso);
                        mDb.SaveChanges();

                        id_recurso = recurso.id;
                    }
                    else
                    {
                        int id_tmp = json.ejercicios[i].recursos[j].id;
                        if (id_tmp < 0) // Si el id es negativo, el recurso fue cargado desde la PC
                        {
                            if (recursosNuevos.ContainsKey(id_tmp)) // Conpruebo que el recurso no haya sido cargado con anterioridad para la actividad
                            {
                                
                                id_recurso = recursosNuevos[id_tmp];
                            }
                            else // En caso de ser nuevo, lo guardo y lo agrego al diccionario para controlar que no se suba de nuevo en la actividad
                            {
                                HttpPostedFileBase file = Request.Files[id_tmp.ToString()];
                                if (file != null)
                                {
                                    id_recurso = mRecursoController.GuardarRecurso(file, file.FileName, user_id, ControllerContext, type).id;
                                    recursosNuevos.Add(id_tmp, id_recurso);
                                }
                                else // Si pasa por acá es porque algo no se cargo
                                {
                                    System.Console.WriteLine("No se guardo el recurso " + id_tmp + " para la actividad " + act.id);
                                }
                            }
                        }
                        else
                        {
                            id_recurso = id_tmp;
                        }
                    }

                    if ((int)json.ejercicios[i].solucion.tipo == (int)SolucionActividad.Opciones && json.ejercicios[i].recursos[j].id == json.ejercicios[i].solucion.respuesta)
                        id_recurso_correcto = id_recurso;

                    ejercicio_x_recurso ej_recurso = new ejercicio_x_recurso()
                    {
                        recurso = id_recurso,
                        ejercicio = ejer.id,
                        pos_top = json.ejercicios[i].recursos[j].top,
                        pos_left = json.ejercicios[i].recursos[j].left,
                        width = json.ejercicios[i].recursos[j].width,
                        height = json.ejercicios[i].recursos[j].height
                    };

                    mDb.ejercicio_x_recurso.AddObject(ej_recurso);
                    mDb.SaveChanges();
                }

                switch ((int)json.ejercicios[i].solucion.tipo)
                {
                    case (int)SolucionActividad.Opciones:
                        ejer.recurso_correcto = id_recurso_correcto;
                        ejer.deletreo = 0;
                        break;
                    case (int)SolucionActividad.Escribir:
                        ejer.texto_solucion = json.ejercicios[i].solucion.respuesta;
                        ejer.deletreo = json.ejercicios[i].solucion.opcion;
                        break;
                    case (int)SolucionActividad.Senias:
                        ejer.senia = json.ejercicios[i].solucion.respuesta;
                        ejer.deletreo = 0;
                        break;
                }

                mDb.ObjectStateManager.ChangeObjectState(ejer, System.Data.EntityState.Modified);
                mDb.SaveChanges();
            }

            mDb.SaveChanges();

            return RedirectToAction("_AsignarActividad", new { id_actividad = act.id, nombre_actividad = act.nombre });
        }

        /// <summary>
        /// Prepara una vista parcial para realizar la asignación de las actividades a los cursos, especificando la fecha
        /// a partir de la cual estarán disponibles.
        /// </summary>
        /// <param name="ids_actividades">IDs de las actividades a las que se les asignarán los cursos.</param>
        /// <param name="actividades">Nombres de las actividades a las que se les asignarán los cursos.</param>
        /// <param name="callbackCancelar">Función JavaScript a la que se llamará si se cancela la operación.</param>
        /// <returns>Partial View: /Actividad/_AsignarActividad</returns>
        public ActionResult _AsignarActividad(int id_actividad, string nombre_actividad, string callbackCancelar = "btnClick_cancelarAsignacion()")
        {
            // guardo los ids en una lista temporal
            Session.Add("ID_Actividad", id_actividad);

            // agrego los ViewBag, que se utilizaran en la vista
            ViewBag.Titulo = nombre_actividad;

            int idDocente = Utiles.Sesion.GetIdUsuarioLogeado(ControllerContext);
            List<int> cAsignados = mDb.actividad_x_curso.Where(x => x.actividad == id_actividad && x.curso1.docente == idDocente).Select(y => y.curso.Value).ToList();
            List<curso> cursos = mDb.curso.Where(x => x.docente == idDocente && !cAsignados.Contains(x.id)).ToList();

            ViewBag.Cursos_DefaultMessage = "Ya has asignado la actividad a todos tus cursos";

            ViewBag.Btn_Cancelar = callbackCancelar;

            return PartialView(cursos);
        }

        /// <summary>
        /// Carga las asignaciones en la base de datos.
        /// </summary>
        /// <param name="ids_cursos">IDs de los cursos que fueron seleccionados.</param>
        /// <param name="fecha_apertura">A partir de que se fecha se podrá realizar la actividad.</param>
        /// <returns>View: /Actividad/Index</returns>
        [HttpPost]
        public ActionResult AsignarActividad(string ids_cursos, string fecha_apertura)
        {
            // recupero los ids de las actividades de la lista temporal.
            int? actividad = Session["ID_Actividad"] as int?;
            Session.Remove("ID_Actividad");

            // obtengo los ids de los cursos.
            string[] cursos = ids_cursos.Split(',');

            foreach (var cur in cursos)
            {
                int idCurso = int.Parse(cur);
                mDb.actividad_x_curso.Select(x => x.actividad == actividad && x.curso == idCurso);


                // cargo los datos a la base de datos.

Peals/Views/Actividad/Index.cshtml
<link href="@Url.Content("~/Content/Styles/WebGrid.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Styles/Actividad.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Styles/reveal.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.reveal.js")"></script>

<div id="actividad_opciones" class="opciones">
	<div id="nuevaActividad">
		<figure>
			<a href="@Url.Action("CrearActividad", "Actividad")">
				<img class="imgConBorde" src="@Url.Content("~/Content/Resources/Actividad/NuevaActividad.png")" width="100" height="125" onclick="location.href='@Url.Action("CrearActividad", "Actividad")';" />
				<figcaption>Nueva Actividad</figcaption>
			</a>
		</figure>
	</div>

	<div id="misRecursos">
		<figure>
			<a href="@Url.Action("ListadoRecursos", "Recurso")">
				<img class="imgConBorde" src="@Url.Content("~/Content/Resources/Actividad/Recursos.png")" width="100" height="125" onclick="location.href='#'" />
				<figcaption>Mis Recursos</figcaption>
			</a>
		</figure>
	</div>
</div>

<section class="actividades">
	<div class="titulo">
		<img src="@Url.Content("~/Content/Resources/Docente/Actividades.jpg")" width="30px" height="25px"/>
		<h2>Actividades</h2>
	</div>
	<div id="list_Actividades" >
		<div class ="searchDiv">
			<input type="text" id="act_buscarNombre" class="buscar" placeholder="Nombre de la actividad" />
			<button type="button" onclick="buscarActividad()">Buscar</button>
		</div>
		<div id="grillaActividades"> @{ Html.RenderAction("_ListadoDeActividades", "Docente"); } </div>
		<div class="acciones">
			<button type="button" id="btn_eliminarActividad" onclick="eliminarActividad()" >Eliminar Actividad</button>
			<button type="button" id="btn_asignarCurso" onclick="asignarCursos()" >Asignar Cursos</button>
		</div>
	</div>
	<div id="list_CursosXActividades">
		<div class ="searchDiv">
			<input type="text" id="curso_buscarNombre" class="buscar" placeholder="Nombre del curso" />
			<button type="button" onclick="buscarCurso()">Buscar</button>
		</div>

		<div id="grillaCursos"></div>
	</div>
</section>
<div id="dialog_asignacion" class="reveal-modal xlarge"></div>

<div id="dialog_eliminar" class="reveal-modal normal">
    <h2>¿Estás seguro de eliminar la actividad?</h2>
    <input type="button" value="Si, estoy seguro" onclick="confirmarEliminarActividad()" />
    <input type="button" value="Mejor no" onclick="cancelarEliminar();" />
</div>

<div id="dialog_desvincular" class="reveal-modal normal">
    <h2>¿Estás seguro de desvincular la actividad del curso?</h2>
    <input type="button" value="Si, estoy seguro" onclick="confirmarDesvincularCurso()" />
    <input type="button" value="Mejor no" onclick="cancelarDesvincular();" />
    <input type="hidden" id="idCursoSeleccionado" />
</div>


<script type="text/javascript">
	var id_ActSeleccionada;
	var nombre_ActSeleccionada;

	var pos_ActSeleccionada;


	function init() {
		var row_actividades = $('#gridActividades').find('tbody > tr');
		row_actividades.bind('click', function (event) {
		    var id = $(this).find('input:hidden').val();
		    var nombre = $(this).find('td:nth-child(2)').text();

		    if (id == id_ActSeleccionada) { // si ya habia sido seleccionada
		        id_ActSeleccionada = -1;
		        nombre_ActSeleccionada = "";

		        $(this).attr('class', (this.rowIndex % 2 == 1) ? 'webgrid-row-style' : 'webgrid-alternating-row');
		        $('.acciones').css('display', 'none');

		        $('#list_CursosXActividades').hide();
		        $('#curso_buscarNombre').empty();

		        $('#list_Actividades').css('border-right', 'none');
		        $('#list_Actividades').animate({ width: "98%" }, function () { $('.searchDiv').children('input').css('width', '85%'); });
		    } else { // si no estaba seleccionada
		        id_ActSeleccionada = id;
		        nombre_ActSeleccionada = nombre;

		        $(this).attr('class', 'webgrid-selected-row');
		        $('.acciones').css('display', 'block');

		        buscarCurso();
		    }

		    if (this.rowIndex != pos_ActSeleccionada) {
		        var rowAnterior = $('#gridActividades tr:nth(' + pos_ActSeleccionada + ')');
		        $(rowAnterior).attr('class', (pos_ActSeleccionada % 2 == 1) ? 'webgrid-row-style' : 'webgrid-alternating-row');

		        pos_ActSeleccionada = this.rowIndex;
		    }
		});

		$('#list_CursosXActividades').hide();
	}




	function buscarActividad() {
		var nombre = $('#act_buscarNombre').val();
		$.post("/Docente/_ListadoDeActividades", { nombre: nombre }, function (data) {
			$('#grillaActividades').empty();
			$('#grillaActividades').append($(data));
		});
	}

	function buscarCurso() {
		var nombre = $('#curso_buscarNombre').val();
		$.post("/Actividad/_CursosPorActividad", { idActividad: id_ActSeleccionada, nombre: nombre }, function (data) {
			$('#grillaCursos').empty();

			if (data == "") {
				$('#list_CursosXActividades').hide();
				$('#list_Actividades').css('border-right', 'none');
				$('#list_Actividades').animate({ width: "98%" }, function () { $('.searchDiv').children('input').css('width', '85%'); });
			}
			else {
				$('#grillaCursos').append($(data));
				$('#list_Actividades').css('border-right', '1px solid gray');
				$('#list_Actividades').animate({ width: "48%" }, function () { $('#list_CursosXActividades').show(); $('.searchDiv').children('input').css('width', '70%'); });
			}
		});
	}

	function asignarCursos() {
		$('#dialog_asignacion').empty();
		$.post("/Actividad/_AsignarActividad", { id_actividad: id_ActSeleccionada, nombre_actividad: nombre_ActSeleccionada, callbackCancelar: "cancelarAsignacion()" }, function (data) {
		    $('#dialog_asignacion').append(data);
		    $('#dialog_asignacion').reveal();

		    applyUIStyles();
		});
	}

	function desvincularCurso(idCurso) {
	    $("#idCursoSeleccionado").val(idCurso);
	    $('#dialog_desvincular').reveal();
	}

	function cancelarAsignacion() {
		$('#dialog_asignacion').trigger('reveal:close');
    }

    function cancelarEliminar() {
        $('#dialog_eliminar').trigger('reveal:close');
    }

    function cancelarDesvincular() {
        $('#dialog_desvincular').trigger('reveal:close');
    }

	function eliminarActividad() {
	    $('#dialog_eliminar').reveal();
	}

	function confirmarEliminarActividad() {
	    $.post("/Actividad/eliminarActividad?idActividad="+id_ActSeleccionada, function (data) {
	        if (data)
	            location.reload();
	        else
	            alert('Ha ocurrido un error');
	    });
	}

	function confirmarDesvincularCurso() {
	    $.post("/Actividad/desvincularCurso?idActividad=" + id_ActSeleccionada + "&idCurso=" + $("#idCursoSeleccionado").val(), function (data) {
	        if (data) {
	            buscarCurso();
	            $('#dialog_desvincular').trigger('reveal:close');
	        }
	        else {
	            alert('Ha ocurrido un error');
	        }
	    });
	}

	function existItem(id) {
		for (var i in ids_actSel) {
			if (ids_actSel[i] == id)
				return i;
		}

		return -1;
	}

	$(document).ready(init);
</script>

Peals/Views/Actividad/VerActividad.cshtml
<link href="@Url.Content("~/Content/Styles/Actividad.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Styles/reveal.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Styles/bootstrap.progressbar.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.reveal.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.inputmask.bundle.js")"></script>
@{
    ViewBag.Title = "PEALS - Actividad";
}
@model List<Peals.Models.ejercicio>
<section class="explicacion">
	<h1>@ViewBag.Titulo</h1>
	<div class="descripcion">
        <div class="titulo">
            <img width="30px" height="25px" src="/Content/Resources/Docente/Docente.PNG">
            <h2> Instrucciones </h2>
        </div>

		<p>@ViewBag.Descripcion</p>
        <a href="#"><img id="verVideoExplicacion" src="/Content/Resources/Actividad/cartel1.png" /></a>
        <a href="#"><img id="verAyudaActividad" src="/Content/Resources/Actividad/cartel2.png" /></a>
	</div>

    
</section>
<section class="detalle">
	
<div id="ejercicio" >
</div>


<div id="divResultado"> </div>


<div id="progresoResolucion">
    <div class="progress">
      <div id="progresoCompletado" class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" style="width:0%">
        Free Space
      </div>
      <div id="progresoRestante" class="progress-bar progress-bar progress-bar-striped active" role="progressbar" style="width:100%">
        Warning
      </div>
    </div>
</div>


</section>
<div id="videoExplicacionEjercicio" class="reveal-modal large">
    <h1>
        Explicación del ejercicio</h1>

         <video width="320" height="240" controls>
              <source src="@Url.Content(ViewBag.Explicacion)" type="video/mp4">
              <source src="@Url.Content(ViewBag.Explicacion)" type="video/ogg">
        </video> 
</div>
<section class="respuesta">    
</section>


@{ Html.BeginForm("VerActividad", "Actividad", FormMethod.Post); }
<!-- Datos globales para guardar -->
<input type="hidden" id="txtIdActividad" name="idActividad" value="@ViewBag.idActividad"/>
<input type="hidden" id="txtIdCurso" name="idCurso" value="@ViewBag.idCurso"/>
<input type="hidden" id="txtTiempo" name="tiempo" value="0" />
<input type="hidden" id="txtNroEjercicio" value="0" />
<input type="hidden" id="txtCantidadEjercicios" name="cantidadEjercicios" value="0" />
<input type="hidden" id="txtCapturarVideo" value="0" />
<input type="hidden" id="txtUsoAyudaActividad" name="usoAyudaActividad" value="0" />
<input type="hidden" id="txtUsoAyudaConsigna" name="usoAyudaConsigna" value="0" />
<input type="hidden" id="txtIntentos" name="intentos" value="1" />
<input type="hidden" id="txtEjNoResueltos" name="ejNoResueltos" value="0" />
<input type="hidden" id="txtDeletreo" value="" />
<!-- --------------------------- -->
@{ Html.EndForm(); }

<script type="text/javascript">
    var ejercicioActual = 0;
    var cantidadEjercicios = 0;
    
    $("#verVideoExplicacion").click(function (e) {
        e.preventDefault();
        $("#videoExplicacionEjercicio").reveal();
        $("#txtUsoAyudaConsigna").val('1');
    });

    $(document).ready(init);

    function init() {

        $.ajax({
            type: "POST",
            url: '/Ejercicio/getCantidadEjercicios',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: JSON.stringify({ idActividad: @ViewBag.idActividad }),
            success: function (data) {
                cantidadEjercicios = data.cantidadEjercicios;
                $("#txtCantidadEjercicios").val(cantidadEjercicios);
                $("#progresoRestante").text(cantidadEjercicios + ' restantes'); //.css( "width", "" );
            },
            error: function () { }
        });

        $("#ejercicio").load("/Ejercicio/_ResolverEjercicio?idActividad=@ViewBag.idActividad&nroEjercicio=0");
    }

</script>

Peals/Views/Actividad/_AsignarActividad.cshtml
<style type="text/css"">
#fecha 
{
    float: left;
    width: 100%;
    margin: 4%;
}

#fecha_apertura 
{
    margin-left: 2%;
}

</style>


@{
	var grillaCursos = new WebGrid(canPage: true, rowsPerPage: 10, canSort: true, ajaxUpdateContainerId: "gridCursos");
	grillaCursos.Bind(Model);
	grillaCursos.Pager(mode: WebGridPagerModes.All,
		firstText: "Primero", lastText: "Ultimo",
		previousText: "Anterior",
		nextText: "Siguiente",
		numericLinksCount: 15);
}

@{ Html.BeginForm("AsignarActividad", "Actividad", FormMethod.Post); }
	<div class="titulo">
		<h2>@ViewBag.Titulo</h2>
        <p id="contador">No hay cursos seleccionados.</p>
	</div>
	<div id="dialog_grillaCursos" >
        @if (grillaCursos.TotalRowCount == 0)
	    {
		    <section style="text-align:center; padding:20px">
			    @ViewBag.Cursos_DefaultMessage
		    </section>
	    }
	    else
	    {
		    @grillaCursos.GetHtml(htmlAttributes: new { id = "gridCursos" },
			    tableStyle: "webgrid",
			    headerStyle: "webgrid-header",
			    footerStyle: "webgrid-footer",
			    alternatingRowStyle: "webgrid-alternating-row",
			    selectedRowStyle: "webgrid-selected-row",
			    rowStyle: "webgrid-row-style",
			    columns: grillaCursos.Columns(
						    grillaCursos.Column(format: @<input type="hidden" name="IDHidden" value="@item.id"/>),
						    grillaCursos.Column(columnName: "institucion1.nombre", header: "Institución", style: "institucion"),
						    grillaCursos.Column(
							    columnName: "ano",
							    header: "Año",
							    format: item => string.Concat(item.ano, item.division)
						    ),
						    grillaCursos.Column(columnName: "nombre", header: "Nombre", style: "nombre"),
						    grillaCursos.Column(format: @<div class="blob"><h2>Descripción</h2><p>@item.descripcion</p></div>)
			    )
		    )
	    }
    </div>

	<div id="fecha">
		<label for="fecha_apertura" >Fecha de Apertura:</label>
		<input type="date" id="fecha_apertura" name="fecha_apertura" placeholder="dd/mm/aaaa" class="datePicker" />
	</div>
@{ Html.EndForm(); }

<div id="acciones">
	<button type="button" id="btn_cancelar" onclick="@ViewBag.Btn_Cancelar">Mejor no</button>
	<button type="button" id="btn_aceptar" onclick="btnClick_Aceptar()">Asignar</button>
</div>

<script type="text/javascript">
	var ids_cursosSel = [];

	function init() {

	    $('input[type="date"]').datepicker();

	    $.datepicker.regional['es'] = {
	        closeText: 'Cerrar',
	        prevText: '<Ant',
	        nextText: 'Sig>',
	        currentText: 'Hoy',
	        changeMonth: true,
	        changeYear: true,
	        yearRange: ' 1967 : * ',
	        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
	        monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
	        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
	        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
	        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
	        weekHeader: 'Sm',
	        dateFormat: 'dd/mm/yy',
	        //dateFormat: 'yy-mm-dd',
	        firstDay: 1,
	        isRTL: false,
	        showMonthAfterYear: false,
	        yearSuffix: ''
	    };
	    $.datepicker.setDefaults($.datepicker.regional['es']);



		var row_cursos = $('#dialog_grillaCursos').find('tbody > tr');
		row_cursos.bind('click', function (event) {
			var pos, id = $('input[type=hidden]', $(this)).val();

			if ((pos = existItem(id)) > -1) { // si ya habia sido seleccionada
				ids_cursosSel.splice(pos, 1);
				$(this).attr('class', (this.rowIndex % 2 == 1) ? 'webgrid-row-style' : 'webgrid-alternating-row');
			} else { // si no estaba seleccionada
				ids_cursosSel.push(id);
				$(this).attr('class', 'webgrid-selected-row');
			}

			if (ids_cursosSel.length > 0) {
				$('#contador').text(ids_cursosSel.length + ' curso(s) seleccionado(s).');
			}
			else {
				$('#contador').text('No hay cursos seleccionados.');
			}
		});

		row_cursos.hover(
			function () { $(this).find('.blob').css('display', 'block'); },
			function () { $(this).find('.blob').css('display', 'none'); }
		);
	}

	function btnClick_Aceptar() {
		var input_cursos = $('<input>').attr({ 'type': 'hidden', 'name': 'ids_cursos', 'value': ids_cursosSel });
		$('form').append(input_cursos);

		if ($("#fecha_apertura").val() == '') {
            alert('Debes ingresar una fecha de apertura de la actividad.');
        }
        else {
            $('form').submit();
        }
	}

	function existItem(id) {
		for (var i in ids_cursosSel) {
			if (ids_cursosSel[i] == id)
				return i;
		}

		return -1;
	}

	$(document).ready(init); 
</script>

Peals/Views/Actividad/_CursosPorActividad.cshtml
@{
    var grillaCursos = new WebGrid(canPage: true, rowsPerPage: 10, canSort: true, ajaxUpdateContainerId: "gridCursos");
    grillaCursos.Bind(Model);
    grillaCursos.Pager(mode: WebGridPagerModes.All,
        firstText: "Primero", lastText: "Ultimo",
        previousText: "Anterior",
        nextText: "Siguiente",
        numericLinksCount: 15);

    @grillaCursos.GetHtml(htmlAttributes: new { id = "gridCursos" },
        tableStyle: "webgrid",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        selectedRowStyle: "webgrid-selected-row",
        rowStyle: "webgrid-row-style",
        columns: grillaCursos.Columns(
            grillaCursos.Column(format: @<input type="hidden" name="IDHidden" value="@item.curso"/>),
            grillaCursos.Column(columnName: "curso1.nombre", header: "Nombre"),
            grillaCursos.Column(columnName: "fecha_apertura", header: "Fecha"),
            grillaCursos.Column(format: @<img onclick="desvincularCurso(@item.curso);" src="../../Content/Resources/General/Cadena.png"/>)
        )
    )
}