Peals/Controllers/BusquedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Peals.Controllers
{
    public class BusquedaController : Controller
    {
        /// <summary>
        /// Devuelve una partial view con un solo campo que se llena con un autocomplete.
        /// </summary>
        /// <param name="accion">Representa la accion que va a ser llamada por ajax (debe devolver un JSON sin que sea un SELECT * porq se rompe) donde buscar con el autocomplete</param>
        /// <param name="controlador"> Controlador donde esta la accion que devuelve el JSON</param>
        /// <param name="label"> El label es lo que se muestra en el desplegable del autocomplete </param>
        /// <param name="value"> Es lo que queda escrito en el input cuando le apretas enter a la opcion del desplegable</param>
        /// <param name="id"> Es un ID comun y corriente</param>
        /// <returns></returns>
        [ActionName ("Autocomplete")]
        public ActionResult Autocomplete(String accion, String controlador, String label, String value, String idList)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;

            return PartialView();
        }


        /// <summary>
        /// Devuelve una partial view con un solo campo que se llena con un autocomplete. Recibe un id que es el que corresponde a la entidad padre de los elementos a filtrar.
        /// </summary>
        /// <param name="idEntidad">Representa la entidad padre, de la cual quieren obtenerse los hijos. Ejemplo: idInstitucion cuando queremos obtener los cursos de esa institucion</param>
        /// <param name="accion">Representa la accion que va a ser llamada por ajax (debe devolver un JSON sin que sea un SELECT * porq se rompe) donde buscar con el autocomplete</param>
        /// <param name="controlador"> Controlador donde esta la accion que devuelve el JSON</param>
        /// <param name="label"> El label es lo que se muestra en el desplegable del autocomplete </param>
        /// <param name="value"> Es lo que queda escrito en el input cuando le apretas enter a la opcion del desplegable</param>
        /// <param name="id"> Es un ID comun y corriente</param>
        /// <returns></returns>
        [ActionName("AutocompleteConPadre")]
        public ActionResult AutocompleteConPadre(String accion, String controlador, String label, String value, String idList, int idEntidad)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion; // + "?idEntidad=" + idEntidad;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;
            ViewBag.idEntidad = idEntidad;

            return PartialView("AutocompleteConPadre");
        }

        /// <summary>
        /// Devuelve una partial view con un solo campo que se llena con un autocomplete.
        /// </summary>
        /// <param name="accion">Representa la accion que va a ser llamada por ajax (debe devolver un JSON sin que sea un SELECT * porq se rompe) donde buscar con el autocomplete</param>
        /// <param name="controlador"> Controlador donde esta la accion que devuelve el JSON</param>
        /// <param name="label"> El label es lo que se muestra en el desplegable del autocomplete </param>
        /// <param name="value"> Es lo que queda escrito en el input cuando le apretas enter a la opcion del desplegable</param>
        /// <param name="id"> Es un ID comun y corriente</param>
        /// <param name="inputName"> Nombre del input donde se escribe lo q se quiere filtrar</param>
        /// <returns></returns>
        [ActionName("AutocompleteCustomInput")]
        public ActionResult AutocompleteCustomInput(String accion, String controlador, String label, String value, String idList, String inputName)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;
            ViewBag.inputName = inputName;

            return PartialView();
        }

        [ActionName("AutocompleteConPadreCustomInput")]
        public ActionResult AutocompleteConPadreCustomInput(String accion, String controlador, String label, String value, String idList, int idEntidad, String inputName)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;
            ViewBag.inputName = inputName;
            ViewBag.idEntidad = idEntidad;

            return PartialView();
        }

    }
}

Peals/Controllers/PruebaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Peals.Models;

namespace Peals.Controllers
{ 
    public class PruebaController : Controller
    {
        private pealsEntities db = new pealsEntities();

        //
        // GET: /Prueba/

        public ViewResult Index()
        {
            var institucion = db.institucion.Include("informacion1").Include("usuario").Include("localidad1");
            return View(institucion.ToList());
        }

        //
        // GET: /Prueba/Details/5

        public ViewResult Details(int id)
        {
            institucion institucion = db.institucion.Single(i => i.id == id);
            return View(institucion);
        }

        //
        // GET: /Prueba/Create

        public ActionResult Create()
        {
            ViewBag.informacion = new SelectList(db.informacion, "id", "contenido");
            ViewBag.administrador = new SelectList(db.usuario, "id", "mail");
            ViewBag.localidad = new SelectList(db.localidad, "id", "nombre");
            return View();
        } 

        //
        // POST: /Prueba/Create

        [HttpPost]
        public ActionResult Create(institucion institucion)
        {
            if (ModelState.IsValid)
            {
                db.institucion.AddObject(institucion);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.informacion = new SelectList(db.informacion, "id", "contenido", institucion.informacion);
            ViewBag.administrador = new SelectList(db.usuario, "id", "mail", institucion.administrador);
            ViewBag.localidad = new SelectList(db.localidad, "id", "nombre", institucion.localidad);
            return View(institucion);
        }
        
        //
        // GET: /Prueba/Edit/5
 
        public ActionResult Edit(int id)
        {
            institucion institucion = db.institucion.Single(i => i.id == id);
            ViewBag.informacion = new SelectList(db.informacion, "id", "contenido", institucion.informacion);
            ViewBag.administrador = new SelectList(db.usuario, "id", "mail", institucion.administrador);
            ViewBag.localidad = new SelectList(db.localidad, "id", "nombre", institucion.localidad);
            return View(institucion);
        }

        //
        // POST: /Prueba/Edit/5

        [HttpPost]
        public ActionResult Edit(institucion institucion)
        {
            if (ModelState.IsValid)
            {
                db.institucion.Attach(institucion);
                db.ObjectStateManager.ChangeObjectState(institucion, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.informacion = new SelectList(db.informacion, "id", "contenido", institucion.informacion);
            ViewBag.administrador = new SelectList(db.usuario, "id", "mail", institucion.administrador);
            ViewBag.localidad = new SelectList(db.localidad, "id", "nombre", institucion.localidad);
            return View(institucion);
        }

        //
        // GET: /Prueba/Delete/5
 
        public ActionResult Delete(int id)
        {
            institucion institucion = db.institucion.Single(i => i.id == id);
            return View(institucion);
        }

        //
        // POST: /Prueba/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            institucion institucion = db.institucion.Single(i => i.id == id);
            db.institucion.DeleteObject(institucion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult ProbandoAutocompletar()
        {
            return View();
        }



        public ActionResult Autocomplete(string term)
        {
            //var items = new[] { "Apple", "Pear", "Banana", "Pineapple", "Peach" };

            //var filteredItems = items.Where(
            //    item => item.IndexOf(term, StringComparison.InvariantCultureIgnoreCase) >= 0
            //    );
            //return Json(filteredItems, JsonRequestBehavior.AllowGet);
            return View();
        }

        public JsonResult Autocomplete2(string parametro)
        {
            var instituciones =
                from i in db.institucion
                where i.nombre.Contains(parametro)
                select new
                {
                    i.nombre,
                    i.id
                };
            return Json(instituciones.Take(5).ToList(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ProbandoAutocompletarAjax()
        {
            return View();
        }

        #region Test Drag-And-Drop

        public ActionResult ProbandoDragAndDrop()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ProbandoDragAndDrop(HttpPostedFileBase imagen)
        {
            HttpPostedFileBase url = Request.Files["imagen"];
            string text = System.IO.Path.GetFileName(Request.Files[0].FileName);

            var stream = Request.InputStream;
            var buffer = new byte[stream.Length];
            stream.Read(buffer, 0, buffer.Length);

            return View();
        }


        public ActionResult ProbandoGaleria()
        {
            ViewBag.imagenes = db.recurso.Where(x => x.tipo_recurso == 1).ToList();
            ViewBag.audios = db.recurso.Where(x => x.tipo_recurso == 2).ToList();
            ViewBag.videos = db.recurso.Where(x => x.tipo_recurso == 3).ToList();

            return View(db.recurso.ToList());
        }

        public ActionResult ProbandoGrabadores()
        {
            return View();
        }

        #endregion
    }
}

Peals/Views/Prueba/Autocomplete.cshtml
        @Html.Action("Autocomplete", "Busqueda", new { accion = "AutocompletePorNombre", controlador = "Institucion", label = "nombre", value = "nombre", id = "id" })

Peals/Views/Prueba/Create.cshtml
@model Peals.Models.institucion

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>institucion</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nombre)
            @Html.ValidationMessageFor(model => model.nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.telefono)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.telefono)
            @Html.ValidationMessageFor(model => model.telefono)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.calle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.calle)
            @Html.ValidationMessageFor(model => model.calle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.altura_calle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.altura_calle)
            @Html.ValidationMessageFor(model => model.altura_calle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.piso)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.piso)
            @Html.ValidationMessageFor(model => model.piso)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.departamento)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.departamento)
            @Html.ValidationMessageFor(model => model.departamento)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.localidad, "localidad1")
        </div>
        <div class="editor-field">
            @Html.DropDownList("localidad", String.Empty)
            @Html.ValidationMessageFor(model => model.localidad)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.administrador, "usuario")
        </div>
        <div class="editor-field">
            @Html.DropDownList("administrador", String.Empty)
            @Html.ValidationMessageFor(model => model.administrador)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.fecha_alta)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.fecha_alta)
            @Html.ValidationMessageFor(model => model.fecha_alta)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.informacion, "informacion1")
        </div>
        <div class="editor-field">
            @Html.DropDownList("informacion", String.Empty)
            @Html.ValidationMessageFor(model => model.informacion)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Peals/Views/Prueba/Delete.cshtml
@model Peals.Models.institucion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>institucion</legend>

    <div class="display-label">nombre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.nombre)
    </div>

    <div class="display-label">telefono</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.telefono)
    </div>

    <div class="display-label">calle</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.calle)
    </div>

    <div class="display-label">altura_calle</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.altura_calle)
    </div>

    <div class="display-label">piso</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.piso)
    </div>

    <div class="display-label">departamento</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.departamento)
    </div>

    <div class="display-label">localidad1</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.localidad1.nombre)
    </div>

    <div class="display-label">usuario</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.usuario.mail)
    </div>

    <div class="display-label">fecha_alta</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.fecha_alta)
    </div>

    <div class="display-label">informacion1</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.informacion1.contenido)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Peals/Views/Prueba/Details.cshtml
@model Peals.Models.institucion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>institucion</legend>

    <div class="display-label">nombre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.nombre)
    </div>

    <div class="display-label">telefono</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.telefono)
    </div>

    <div class="display-label">calle</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.calle)
    </div>

    <div class="display-label">altura_calle</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.altura_calle)
    </div>

    <div class="display-label">piso</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.piso)
    </div>

    <div class="display-label">departamento</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.departamento)
    </div>

    <div class="display-label">localidad1</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.localidad1.nombre)
    </div>

    <div class="display-label">usuario</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.usuario.mail)
    </div>

    <div class="display-label">fecha_alta</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.fecha_alta)
    </div>

    <div class="display-label">informacion1</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.informacion1.contenido)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Peals/Views/Prueba/ProbandoAutocompletar.cshtml
@{
    ViewBag.Title = "ProbandoAutocompletar";
}

    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.9.1.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/jquery.ui.core.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/jquery.ui.widget.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/jquery.ui.position.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/jquery.ui.menu.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/jquery.ui.autocomplete.js") type="text/javascript"></script>
	
    
    <label for="somevalue">Some value:</label><input type="text" id="somevalue" name="somevalue"/>
    
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
            $('#somevalue').autocomplete({
                source: '@Url.Action("Autocomplete", "Prueba")'
            });
        })
    </script>

Peals/Views/Prueba/ProbandoDragAndDrop.cshtml
<style>
h2
{
    border-bottom: 2px solid #3966A2;
    color: #3966A2;
    margin: 5px;
}    

.section { clear: both }    

.column { height: 150px; width: 150px; cursor: move; }

.column, table
{
    margin: 15px;
    float: left;
    border: 2px solid #666666;
    background-color: #ccc;
    margin-right: 5px;
    -webkit-border-radius: 10px;
    -ms-border-radius: 10px;
    -moz-border-radius: 10px;
    border-radius: 10px;
    -webkit-box-shadow: inset 0 0 3px #000;
    -ms-box-shadow: inset 0 0 3px #000;
    box-shadow: inset 0 0 3px #000;
    text-align: center;
}

.column header, table thead 
{
    color: #fff;
    text-shadow: #000 0 1px;
    box-shadow: 5px;
    padding: 5px;
    background: -moz-linear-gradient(left center, rgb(0,0,0), rgb(79,79,79), rgb(21,21,21));
    background: -webkit-gradient(linear, left top, right top,
                                color-stop(0, rgb(0,0,0)),
                                color-stop(0.50, rgb(79,79,79)),
                                color-stop(1, rgb(21,21,21)));
    background: -webkit-linear-gradient(left center, rgb(0,0,0), rgb(79,79,79), rgb(21,21,21));
    background: -ms-linear-gradient(left center, rgb(0,0,0), rgb(79,79,79), rgb(21,21,21));
    border-bottom: 1px solid #ddd;
    -webkit-border-top-left-radius: 10px;
    -moz-border-radius-topleft: 10px;
    -ms-border-radius-topleft: 10px;
    border-top-left-radius: 10px;
    -webkit-border-top-right-radius: 10px;
    -ms-border-top-right-radius: 10px;
    -moz-border-radius-topright: 10px;
    border-top-right-radius: 10px;
    text-align:center;
}

.table { width: 90% }
.table tbody > tr:hover 
{
    cursor: pointer;
    background: #ffff99;
}

.filaSeleccionada { background: #ffff99 }

.leftPanel
{
    width: 48%;
    float: left;
}

.rightPanel
{
    width: 48%;
    float: right;
    border-left: 1px solid gray;
}

.lista 
{
    border-top: 1px solid ffff99;
    border-bottom: 1px solid ffff99;
    height: 200px;
    overflow: auto;
}

.lista li 
{ 
    border-bottom: 1px solid gray;
    padding: 10px;
}
</style>

@{
    ViewBag.Title = "ProbandoDragAndDrop";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/DragAndDrop.js")"></script>

<div id="simpleDnD" class="section">
  <h2>Drag and Drop de un sólo element</h2>
  <div class="column"><header>A</header></div>
  <div class="column"><header>B</header></div>
  <div class="column"><header>C</header></div>
</div>

<div id="multipleDnD" class="section">
  <h2>Drag and Drop de varios elements a la vez</h2>
  <div class="leftPanel">
      <p>Arrastra las peliculas al panel de la derecha</p>
      <table class="table">
        <thead>
            <tr><th>Pelicula</th><th>Genero</th><th>Puntuacio</th></tr>
        </thead>
        <tbody>
            <tr><td>¿Que paso ayer? Parte 1</td><td>Comedia</td><td>5</td></tr>
            <tr><td>¿Que paso ayer? Parte 2</td><td>Comedia</td><td>4</td></tr>
            <tr><td>¿Que paso ayer? Parte 3</td><td>Comedia</td><td>3</td></tr>
        </tbody>
      </table>
  </div>
  <div class="rightPanel">
      <p>En este panel se mostrarán los nombres de la películas arrastradas</p>
      <ul class="lista"></ul>
  </div>
</div>

@{ Html.BeginForm("ProbandoDragAndDrop", "Prueba", FormMethod.Post, new { enctype="multipart/form-data" }); }
<div id="fileDnD" class="section">
  <h2>Drag and Drop de archivos</h2>
  <div class="column"><img src="../../Content/Resources/Uploads/sin_imagen.jpg" width="100%" height="100%"/></div>
  <div class="column"><img src="../../Content/Resources/Uploads/sin_imagen.jpg" width="100%" height="100%" /></div>
  <div class="column"><img src="../../Content/Resources/Uploads/sin_imagen.jpg" width="100%" height="100%" /></div>
</div>
<input type="file" id="imagen" name="imagen" style="display:none"/>
<input type="submit" value="Subir Imagenes Cargadas" style="margin-top:20px" />
@{ Html.EndForm(); }

<script type="text/javascript">
    // Esta función es llamada cuando se suelta el elemento sobre un objeto dragueable.
    // Corresponde al DIV "simpleDnd"
    // [Parameter= "dropElement"]: es donde se suelta el elemento
    // [Parameter= "data"]: es el elemento que se estaba moviendo.
    function dropEndSimpleCallback(dropElement, data) {
        // solo una pregunta de control para asegurarse que no me pasen datos incorrectos.
        if (dropElement.parentElement != data.parentElement) return;

        // intercambio el contenido de cada div
        var tmp = dropElement.innerHTML;
        dropElement.innerHTML = data.innerHTML;
        data.innerHTML = tmp;
    }

    // Esta función es llamada cuando se sultan unos o varios elementos sobre un objeto dragueable.
    // Corresponde al DIV "multipleDnd"
    // [Parameter= "dropElement"]: es donde se suelta el elemento
    // [Parameter= "data"]: es el elemento que se estaba moviendo.
    function dropEndMultipleCallback(dropElement, data) {
        // obtengo el nombre de la pelicula
        var peliculaSeleccionada = $(data).find('td:first').text();

        // verifico si los datos pasados son correctos.
        if (dropElement.parentElement == data.parentElement || peliculaSeleccionada == "") return;

        // veo si el elemento que esta siendo dragueado, existe en el array. En caso de no existir, lo agrego.
        var pos = data.rowIndex;
        if (existItem(pos) == -1) {
            peliculasSeleccionadas.push({ 'pos': pos, 'obj': peliculaSeleccionada });
            $(data).attr('class', 'filaSeleccionada');
        }

        // agrego las peliculas seleccionadas a la lista.
        for (var i in peliculasSeleccionadas) {
            row = peliculasSeleccionadas[i].obj;
            dropElement.innerHTML += '<li>' + row + '</li>';
        }
    }

    // Creo un array que contendra todos los elementos que van a ser movidos en conjunto. 
    var peliculasSeleccionadas = new Array();
    // Función que controla los click sobre las filas de la tabla, agregando o eliminando 
    // (según corresponda) cada fila del array "peliculasSeleccionadas".
    function onTableRowClick(event){
        var i, pos = this.rowIndex;
        if((i = existItem(pos)) > -1){ // si ya habia sido seleccionada
            peliculasSeleccionadas.splice(i, 1);
            $(this).removeAttr('class');
        } else{ // si no estaba seleccionada
            peliculasSeleccionadas.push({ 'pos': pos, 'obj': $(this).find('td:first').text() });
            $(this).attr('class', 'filaSeleccionada');
        }
    }

    // Función auxiliar para controlar los elementos dentro de un array.
    function existItem(pos){
        for (var i in peliculasSeleccionadas){
            if (peliculasSeleccionadas[i].pos == pos) 
                return i;
        }

        return -1;
    }

    // Esta función es llamada cuando se suelta una imagen del escritorio, sobre una imagen.
    // Corresponde al DIV "fileDnd"
    // [Parameter= "files"]: es la lista de archivos que se arrastraron 
    // [Parameter= "element"]: es el elemento donde se suelta el archivo
    function dropEndFileCallback(element, files) {
        // cargo la imagen en el <input type= file .../> para que se puedan subir al servidor.
//        $('#imagen').list = files;
//        $('#imagen').value = files.name;
//        $('#imagen').select();
        $('#imagen') = files[0];
    }

    // Se encarga de agregar las propiedades de Drag and Drop a los elementos deseados.
    function agregarDragAndDrop() {
        /**************** Simple DnD *******************/
        var simpleDrag = $('.column'); // obtengo todos los elementos con class="column"
        simpleDrag.setDnD(dropEndSimpleCallback); // les agrego la propiedad de dragueable

        /*************** Multple DnD *******************/
        var tabla = $('tbody > tr', '.table'); // obtengo las filas de la tabla dentro del tbody
        tabla.setDnD(dropEndMultipleCallback); // les agrego la propiedad de dragueable 
        tabla.bind('click', onTableRowClick);  // les agrego el evento click
        
        var lista = $('.lista');               // obtengo la lista 
        lista.setDnD(dropEndMultipleCallback); // les agrego la propiedad de dragueable

        /**************** File DnD ********************/
        // hago que los elemtos "img" puedan recibir archivos desde el escritorio, y establesco la 
        // propieded "autoload" como true.
        $('img').setFileDnD(dropEndFileCallback, true);
    }

    $(document).ready(agregarDragAndDrop);
</script>