Peals/Controllers/BusquedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Peals.Controllers
{
    public class BusquedaController : Controller
    {
        /// <summary>
        /// Devuelve una partial view con un solo campo que se llena con un autocomplete.
        /// </summary>
        /// <param name="accion">Representa la accion que va a ser llamada por ajax (debe devolver un JSON sin que sea un SELECT * porq se rompe) donde buscar con el autocomplete</param>
        /// <param name="controlador"> Controlador donde esta la accion que devuelve el JSON</param>
        /// <param name="label"> El label es lo que se muestra en el desplegable del autocomplete </param>
        /// <param name="value"> Es lo que queda escrito en el input cuando le apretas enter a la opcion del desplegable</param>
        /// <param name="id"> Es un ID comun y corriente</param>
        /// <returns></returns>
        [ActionName ("Autocomplete")]
        public ActionResult Autocomplete(String accion, String controlador, String label, String value, String idList)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;

            return PartialView();
        }


        /// <summary>
        /// Devuelve una partial view con un solo campo que se llena con un autocomplete. Recibe un id que es el que corresponde a la entidad padre de los elementos a filtrar.
        /// </summary>
        /// <param name="idEntidad">Representa la entidad padre, de la cual quieren obtenerse los hijos. Ejemplo: idInstitucion cuando queremos obtener los cursos de esa institucion</param>
        /// <param name="accion">Representa la accion que va a ser llamada por ajax (debe devolver un JSON sin que sea un SELECT * porq se rompe) donde buscar con el autocomplete</param>
        /// <param name="controlador"> Controlador donde esta la accion que devuelve el JSON</param>
        /// <param name="label"> El label es lo que se muestra en el desplegable del autocomplete </param>
        /// <param name="value"> Es lo que queda escrito en el input cuando le apretas enter a la opcion del desplegable</param>
        /// <param name="id"> Es un ID comun y corriente</param>
        /// <returns></returns>
        [ActionName("AutocompleteConPadre")]
        public ActionResult AutocompleteConPadre(String accion, String controlador, String label, String value, String idList, int idEntidad)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion; // + "?idEntidad=" + idEntidad;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;
            ViewBag.idEntidad = idEntidad;

            return PartialView("AutocompleteConPadre");
        }

        /// <summary>
        /// Devuelve una partial view con un solo campo que se llena con un autocomplete.
        /// </summary>
        /// <param name="accion">Representa la accion que va a ser llamada por ajax (debe devolver un JSON sin que sea un SELECT * porq se rompe) donde buscar con el autocomplete</param>
        /// <param name="controlador"> Controlador donde esta la accion que devuelve el JSON</param>
        /// <param name="label"> El label es lo que se muestra en el desplegable del autocomplete </param>
        /// <param name="value"> Es lo que queda escrito en el input cuando le apretas enter a la opcion del desplegable</param>
        /// <param name="id"> Es un ID comun y corriente</param>
        /// <param name="inputName"> Nombre del input donde se escribe lo q se quiere filtrar</param>
        /// <returns></returns>
        [ActionName("AutocompleteCustomInput")]
        public ActionResult AutocompleteCustomInput(String accion, String controlador, String label, String value, String idList, String inputName)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;
            ViewBag.inputName = inputName;

            return PartialView();
        }

        [ActionName("AutocompleteConPadreCustomInput")]
        public ActionResult AutocompleteConPadreCustomInput(String accion, String controlador, String label, String value, String idList, int idEntidad, String inputName)
        {
            //armo la ruta para acceder a la accion desde donde se devuelve el JSON
            ViewBag.accion = "/" + controlador + "/" + accion;
            //cargo los valores label, value e id que se utilizan para mostrar los datos en el autocomplete
            ViewBag.label = label;
            ViewBag.value = value;
            ViewBag.id = idList;
            ViewBag.inputName = inputName;
            ViewBag.idEntidad = idEntidad;

            return PartialView();
        }

    }
}

Peals/Controllers/DocenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Peals.Models;

namespace Peals.Controllers
{
    
    public class DocenteController : UsuarioController
    {

        #region VIEWS

        /// <summary>
        /// Crea la vista principal del Docente. 
        /// </summary>
        /// <returns>GET: /Docente/Index</returns>
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult Index()
        {
            // agrega tres vistas parciales para "Actividades", "Cursos" y "Solicitudes"
            return View();
        }

        /// <summary>
        /// Prepara la vista para registrar a un nuevo docente.
        /// </summary>
        /// <returns>GET: /Docente/NuevoDocente</returns>
        public ActionResult NuevoDocente()
        {
            // recupero las especialidades y las guardo en el diccionario
            var especialidades =
                from e in mDb.especialidad
                select e;

            ViewData["especialidad"] = new SelectList(especialidades.ToList(), "id", "nombre");

            // devuelvo la vista anexando en el view la vista parcial de /Usuario/NuevoUsuario.
            return View();
        }

        /// <summary>
        /// Prepara la vista para realizar la edición de los datos del docente.
        /// </summary>
        /// <returns>GET: /Docente/EditarDocente</returns>
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult EditarDocente()
        {
            String mailUsuario = User.Identity.Name;
            usuario usuario = mDb.usuario.Single(u => u.mail == mailUsuario);
            ViewBag.especialidad = new SelectList(mDb.especialidad, "id", "nombre", usuario.especialidad);

            return View();
        }

        /// <summary>
        /// Prepara la vista para poder dar de baja al docente.
        /// </summary>
        /// <see cref="Usuario/DarBajaUsuario"/>
        /// <returns>GET: Docente/DarBajaDocente</returns>
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult DarBajaDocente()
        {
            return View();
        }


        /// <summary>
        /// Devuelvo un listado de todas las actividades creadas por el docente.
        /// </summary>
        /// <param name="nombre">Opcional, es el nombre de la actividad y se usa para filtrar los resultados.</param>
        /// <returns>PartialView: /Docente/_ListadoDeActividades</returns>
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult _ListadoDeActividades(string nombre= "")
        {
            int id = Utiles.Sesion.GetIdUsuarioLogeado(ControllerContext);

            var actividades = mDb.actividad.Where(x => x.docente == id && (x.estado == (int)EstadoActividad.Alta || x.estado == (int)EstadoActividad.ConHistorial) && x.nombre.Contains(nombre.ToLower()));

            return PartialView(actividades.ToList());
        }

        /// <summary>
        /// Devuelve un listado con todos los docentes registrados en el sistema, diciendo además
        /// cuales de ellos trabajan con la institución pasada por parámetro.
        /// </summary>
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult TodosLosDocentes(int idInstitucion)
        {
            ViewBag.idInstitucion = idInstitucion;
            var institucion = mDb.institucion.First(x => x.id == idInstitucion);

            var docentes =
                from d in mDb.usuario
                join di in mDb.docente_x_institucion on d.id equals di.docente into ljoin // LEFT JOIN
                from lj in ljoin.DefaultIfEmpty()
                where d.tipo_usuario == (int)TipoDeUsuario.Docente
                let tieneInstitucion = lj.docente.HasValue // Var Aux para que indica si un docente se encuentra trabajando en una institución.
                group d.id by new { d.id, d.nombre, d.apellido, d.mail, d.especialidad1, tieneInstitucion } into d
                select new
                {
                    Id = d.Key.id,
                    Nombre = string.Concat(d.Key.apellido, ", ", d.Key.nombre),
                    Mail = d.Key.mail,
                    Especialidad = d.Key.especialidad1.nombre,
                    CantInstituciones = (d.Key.tieneInstitucion) ? d.Count() : 0,
                    TrabajaEnInstitucion = (from inst in mDb.docente_x_institucion where inst.docente == d.Key.id && inst.institucion == idInstitucion select 1).Count(),
                    SolicitudesEnviadas = (
                        from m in mDb.mensaje 
                        from md in mDb.mensaje_x_destinatario
                        where m.id == md.mensaje1.id
                            && m.emisor_mensaje == institucion.administrador 
                            && m.tipo_mensaje == 2 //Solicitud
                            && (m.estado_mensaje == 1 || m.estado_mensaje == 2) //
                            && m.tipo_solicitud == 3 //inscripcion docente
                            && md.destinatario == d.Key.id
                        select m.id
                        ).Count() 
                };

            return View(docentes);
        }

        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult DiacOSeguimiento()
        {
            return View();
        }

        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult Reportes()
        {
            Int32 idUsuario = Utiles.Sesion.GetIdUsuarioLogeado(ControllerContext);
            //var cursos =
            //    from c in mDb.curso
            //    where c.docente == idUsuario
            //    select c;
            //ViewData["cursos"] = new SelectList(cursos.ToList(), "id", "nombre");

            ViewBag.docente = idUsuario;
            return View();
        }


        #endregion

        #region ABM

        /// <summary>
        /// Guarda los datos del docente en la base de datos.
        /// </summary>
        /// <param name="docente">Docente a registrar</param>
        /// <returns>Devuelve la vista Index del docente o un mensaje en caso de error.</returns>
        [HttpPost]
        public ActionResult NuevoDocente(usuario docente)
        {
            // Si el modelo es válido, guardo el usuario; de lo contrario, devuelvo null.
            return (ModelState.IsValid) ? GuardarUsuario(docente, View().ViewName, ControllerContext) : View();
        }

        /// <summary>
        /// Aplica los cambios a los datos del docente.
        /// </summary>
        /// <param name="docente">Objecto que contiene los cambios aplicados por el docente.</param>
        /// <returns>Redirecciona a la página Index o muestra un mensaje en caso de error.</returns>
        [HttpPost]
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult EditarDocente(usuario docente)
        {
            // Si el modelo es válido, guardo los cambios; de lo contrario, vuelvo a la vista.
            return (ModelState.IsValid) ? ModificarUsuario(docente) : View();
        }

        /// <summary>
        /// Guarda el docente dado de baja en la base de datos.
        /// </summary>
        /// <param name="docente">Docente a dar de baja</param>
        /// <returns>Devuelve la vista Index del home o un mensaje en caso de error.</returns>
        [HttpPost]
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult DarBajaDocente(usuario doc)
        {
            //seteo el modelo a lo demas controladores
            mActividadController.setModelo(mDb);
            mCursoController.setModelo(mDb);
            mInstitucionController.setModelo(mDb);
            mRecursoController.setModelo(mDb);

            // debido a que los cambios sólo se pueden aplicar al usuario original, lo recupero de la base de datos.
            int idUsr = Utiles.Sesion.GetIdUsuarioLogeado(ControllerContext);
            usuario docente = mDb.usuario.Single(usr => usr.id == idUsr);

            //Doy de baja a los recursos
            mRecursoController.DarDeBajaRecursosDocente(docente.id);

            // Doy de baja a las actividades del docente.
            mActividadController.DarDeBajaActividadesDocente(docente.id);

            // borro el docente de las actividades con curso.
            //mActividadController.BorrarInscripcionActividadesDocenteConCurso(docente.id);

            // Doy de baja a los cursos del docente
            mCursoController.DarDeBajaCursosDocente(docente.id);

            // borro el docente de las actividades sin curso pero con historial.
            //mActividadController.BorrarInscripcionActividadesDocenteSinCurso(docente.id);

            // borro las actividades del docente que no tengan curso y no tengan historial.
            //mActividadController.BorrarActividadesDocenteSinHistorial(docente.id);
            // borro el docente de los cursos
            //mCursoController.BorrarInscripcionCursosDocente(docente.id);

            // borro las inscripciones del docente a las instituciones
            mInstitucionController.BorrarInscripcionInstitucionesDocente(docente.id);

            // doy de baja al usuario
            this.DarBajaUsuario(docente);

            if (mDb.SaveChanges() == 0)
            {
                ModelState.AddModelError("ErrorModificar", "Ha ocurrido un error mientras se intentaba modificar sus datos. Por favor, intentelo de nuevo más tarde.");
                return View();
            }

            // Si se pudo dar de baja al usuario, cierro sesión y lo redirecciono a la pagina principal.
            return this.CerrarSesion();
        }

        #endregion

        /// <summary>
        /// INCOMPLETO - SE ENCARGARIA DE PREPARA LA VISTA PARA LA GESTION DE LAS 
        /// ACTIVIDADES POR PARTE DEL DOCENTE.
        /// </summary>
        [Authorize(Roles = "Docente, Administrador")] 
        public ActionResult GestionDeActividades()
        {

Peals/Views/Diac/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style>
    .opciones div
    {
        float: left;
        margin-left: 6em;
        width: 20%;
    }
    
    select
    {
        width: 48em;
        margin-left: 6em;
        margin-top: 1em;
        margin-bottom: 1em;
    }
</style>
<div id="tituloPagina">
    <h1>
        Listado de D.I.A.C</h1>
</div>
<div id="explicacionTituloPagina">
    <h1>
        Administre el D.I.A.C. de su institución para obtener un buen seguimiento de sus
        alumnos.
    </h1>
</div>
@Html.DropDownList("institucion", ViewData["institucion"] as IEnumerable<SelectListItem>)
<div id="diac_opciones" class="opciones">
    <div id="verDiacActual">
        <figure>
                <img class="imgConBorde" src="@Url.Content("~/Content/Resources/Administrador/NuevoCurso.png")" width="100" height="125" />
                <figcaption"><a href="#">Ver D.I.A.C. Actual</a></figcaption>
            </figure>
    </div>
    <div id="modificarDiacActual">
        <figure>
                <img class="imgConBorde" src="@Url.Content("~/Content/Resources/General/Profesor.jpg")" width="100" height="125" />
                <figcaption><a href="#">Modificar D.I.A.C. Actual</a></figcaption>
            </figure>
    </div>
    <div id="agregarDiac">
        <figure>
               <img class="imgConBorde" src="@Url.Content("~/Content/Resources/Docente/Seguimiento.jpg")" width="100" height="125" />
               <figcaption><a href="#">Nuevo D.I.A.C.</a></figcaption>
           </figure>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        cambioCombo();
    });
    
    function cambioCombo() {
        var id_institucion = $("#institucion").val();

        $.ajax({
            type: "POST",
            url: '/Diac/TieneDiac',
            data: JSON.stringify({ idInstitucion: id_institucion }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success:
                function (data) {
                    if (data == false) {
                        $("#verDiacActual").show();
                        $("#modificarDiacActual").show();
                        $("#agregarDiac").hide();

                    }
                    else {
                        $("#verDiacActual").hide();
                        $("#modificarDiacActual").hide();
                        $("#agregarDiac").show();
                    }
                },
            error: function () { alert('error'); }
        });
    }

    $("#institucion").change(function () {
        cambioCombo();
    });




    $("#agregarDiac").click(function (e) {
        e.preventDefault();
        location.href = '/Diac/NuevoDiac?idInstitucion=' + $("#institucion").val();
    });

    $("#verDiacActual").click(function (e) {
        e.preventDefault();
        location.href = '/Diac/VerDiacCreada?idInstitucion=' + $("#institucion").val();
    });

    $("#modificarDiacActual").click(function (e) {
        e.preventDefault();
        location.href = '/Diac/ModificarDiac?idInstitucion=' + $("#institucion").val();
    });
    
</script>

Peals/Views/Diac/MenuDiacCurso.cshtml
@{
    ViewBag.Title = "DIAC - MENU CURSO";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.reveal.js")"></script>
<link href="@Url.Content("~/Content/Styles/reveal.css")" rel="stylesheet" type="text/css" />

<style type="text/css">
    #fechasFiltro input
    {
        margin-right: 0.5em;
        float: left;
    }
    
    #fechasFiltro
    {
        float: left;
        margin-top: 1em;
        width: 100%;
    }
    
    #fechasFiltro div
    {
        margin-right: 0.5em;
        width: fix;
        float: left;
    }
    
    #panelDiacResueltos
    {
        float: left;
        width: 100%;
        margin-top: 4em;
        margin-bottom: 4em;
    }
    #divDiacResueltas, #divAlumnos
    {
        float: left;
        display: none;
        width: 100%;
        margin-bottom:2em;
    }
    
    #divComboSelector
    {
        float: left;
        margin-bottom: 2em;
        margin-right: 0.5em;
        width: 100%;
    }
    #divComboSelector select
    {
        margin-left: 1em;
    }
</style>
<div id="tituloPagina">
    <h1>
        DIAC Curso @ViewBag.nombreCurso</h1>
</div>
<div id="explicacionTituloPagina">
    <h1>
        En esta sección usted podrá efectuar el seguimiento de sus alumnos, completando
        las DIAC definidas por el administrador de la institución o las plantillas de seguimiento
        que usted puede crear.
    </h1>
</div>
<div id="divComboSelector">
    Mostrar:
    <select id="comboMostrar">
        <option id="1">Alumnos</option>
        <option id="2">Resoluciones</option>
    </select>
    <div id="fechasFiltro">
        <div class="filtroFechas">
            Fecha Desde:</div>
        <input type="text" id="fechaDesde" class="datePicker filtroFechas" />
        <div class="filtroFechas">
            Fecha Hasta:</div>
        <input type="text" id="fechaHasta" class="datePicker filtroFechas" />
        <div>
            Alumno:</div>
        <input type="text" id="filtroAlumno" />

        <input id="btnBuscar" type="button" value="Buscar" style="font-size: 1em !important;" />
    </div>
</div>
<div id="divDiacResueltas">
    <div id="panelDiacResueltos">
    </div>
</div>
<div id="divAlumnos">
    <div id="grillaAlumnos">
    </div>
</div>

<div id="seleccionarVersion" class="reveal-modal large">
hola
</div>

<script type="text/javascript">
    $(document).ready(function () {
    
});
    

    $( document ).ready(function() {
        $("#divAlumnos").show("slow");
        $(".filtroFechas").hide("slow");
        $("#divDiacResueltas").hide("slow", function() {
           
            $("#btnBuscar").click();
        });        
    });
    
    $(".datePicker").datepicker();

    $("#btnBuscar").click(function () {
        if($("#comboMostrar").val() == "Alumnos"){
            $("#grillaAlumnos").load("/Llenadoseguimiento/_AlumnosResolucionCurso?fechaDesde=" + $("#fechaDesde").val() + "&fechaHasta=" + $("#fechaHasta").val() + "&idCurso=" + @ViewBag.idCurso  + "&identificador=DIAC&alumno=" + $("#filtroAlumno").val());
        }
        else {
            $("#panelDiacResueltos").load("/Llenadoseguimiento/_DiacResueltas?fechaDesde=" + $("#fechaDesde").val() + "&fechaHasta=" + $("#fechaHasta").val() + "&idCurso=" + @ViewBag.idCurso  + "&identificador=DIAC&alumno=" + $("#filtroAlumno").val());
        }
    });

    $("#comboMostrar").change(function() {
        if($("#comboMostrar").val() == "Alumnos"){
            $(".filtroFechas").hide("slow");
            $("#divDiacResueltas").hide("slow");
            $("#divAlumnos").show("slow");
            $("#btnBuscar").click();
        }
        else {
            $(".filtroFechas").show("slow");
            $("#divDiacResueltas").show("slow");
            $("#divAlumnos").hide("slow");
            $("#btnBuscar").click();
        }
    });


        


</script>

Peals/Views/Diac/MenuResolucion.cshtml
@{
    ViewBag.Title = "Menú Resolución";
}
<style>
    .opciones div
    {
        float: left;
        margin-left: 6em;
        width: 20%;
    }
    
    select
    {
        width: 48em;
        margin-left: 6em;
        margin-top: 1em;
        margin-bottom: 1em;
    }
    
    button {
        font-size: 0.8em !important;
    }
    
    .searchDiv select {
        width: 16% !important;
    }
    
    #docente_cursos 
    {
        width:85% !important;
    }
</style>

<link href="@Url.Content("~/Content/Styles/Docente.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Styles/WebGrid.css")" rel="stylesheet" type="text/css" />

<div id="tituloPagina">
    <h1>Menú Resolución</h1>
</div>
<div id="explicacionTituloPagina">
    <h1>
        En esta sección usted podrá efectuar el seguimiento de sus alumnos, completando las DIAC definidas por el administrador de la institución.
    </h1>
</div>


	<div id="docente_cursos">
		<div class="titulo">
			<img src="@Url.Content("~/Content/Resources/Docente/MisCursos.jpg")" width="30px" height="28px" />
			<h2>Mis Cursos</h2>
		</div>
		<div class ="searchDiv">
			<label for="curso_buscarPor">Buscar por</label>
			<select id="curso_buscarPor" onchange="cambiarAutocomplete(this, $('#reemplazable_cursos'));">
				<option value="Institucion">Institución</option>
				<option value="Curso">Curso</option>
			</select>
			<div id="reemplazable_cursos"></div> 
			<button type="button" onclick="buscarCursos();">Buscar</button>
		</div>
		<div id="grillaCursos" style="width:95%; margin:10px">@{Html.RenderAction("_Cursos", "Docente");}</div>
		<div id="op_cursos" >
			<button type="button" id="btn_agregarActividades" onclick="mostrarActividades()">Agregar Actividades</button>
			<button type="button" id="btn_agregarAlumnos" onclick="agregarAlumnos()">Agregar Alumnos</button>
		</div>
	</div>

<script type="text/javascript">
    
    
    
    
    $("#agregarDiac").click(function (e) {
        e.preventDefault();
        location.href = '/Diac/NuevoDiac?idInstitucion=' + $("#institucion").val();
    });

    $("#verDiacActual").click(function (e) {
        e.preventDefault();
        location.href = '/Diac/VerDiacCreada?idInstitucion=' + $("#institucion").val();
    });

    $("#modificarDiacActual").click(function (e) {
        e.preventDefault();
        location.href = '/Diac/ModificarDiac?idInstitucion=' + $("#institucion").val();
    });


    function buscarCursos() {
        var searchCriteria = $('#curso_buscarPor').val();
        var searchValue = $('input', '#reemplazable_cursos').val();

        var url = '@Url.Action("_Cursos", "Docente")' + '?searchCriteria=' + searchCriteria + '&searchValue=' + searchValue;
        url = url.replace(/ /g, '%20');

        $('#grillaCursos').load(url);
    }


    function modificarPlaceHolder(placeHolder, autocomplete) {
        $(autocomplete).fadeIn('slow', function () {
            $('input', autocomplete).attr('placeholder', placeHolder);
        });
    }

    function cambiarAutocomplete(select, autocomplete) {
        $(autocomplete).fadeOut();

        var placeHolder = "";
        switch ($(select).val()) {
            case "Alumno":
                placeHolder = "Nombre o E-Mail del Alumno";
                $(autocomplete).load(
					'@Html.Raw(@Url.Action("Autocomplete", "Busqueda", new { accion = "Autocomplete_Alumno", controlador = "Docente", label = "Label", value = "Value", idList = "Id" }))',
					modificarPlaceHolder(placeHolder, autocomplete)
				);
                break;
            case "Actividad":
                placeHolder = "Nombre de la Actividad";
                $(autocomplete).load(
					'@Html.Raw(@Url.Action("Autocomplete", "Busqueda", new { accion = "Autocomplete_NombreActividad", controlador = "Docente", label = "Label", value = "Value", idList = "Id" }))',
					modificarPlaceHolder(placeHolder, autocomplete)
				);
                break;
            case "Institucion":
                placeHolder = "Nombre de la Institución";
                $(autocomplete).load(
					'@Html.Raw(@Url.Action("Autocomplete", "Busqueda", new { accion = "Autocomplete_NombreInstitucion", controlador = "Docente", label = "Label", value = "Value", idList = "Id" }))',
					modificarPlaceHolder(placeHolder, autocomplete)
				);

                break;
            case "Curso":
                placeHolder = "Nombre del Curso";
                $(autocomplete).load(
					'@Html.Raw(@Url.Action("Autocomplete", "Busqueda", new { accion = "Autocomplete_NombreCurso", controlador = "Docente", label = "Label", value = "Value", idList = "Id" }))',
					modificarPlaceHolder(placeHolder, autocomplete)
				);

                break;
        }
    }


    $(document).ready(function () {
        $('#curso_buscarPor').val('Institucion');
        cambiarAutocomplete($('#curso_buscarPor'), $('#reemplazable_cursos'));




        $("#gridCursos td").click(function () {
            var idCursoSeleccionado = $(this).parent().find(".idHidden").val();
            var url = "/Diac/MenuDiacCurso?idCurso=" + idCursoSeleccionado;
            window.location.href = url;
        });


    });

        


</script>

Peals/Views/Diac/_Cursos.cshtml
@{
	var grillaCursos = new WebGrid(canPage: true, rowsPerPage: 10, canSort: true, ajaxUpdateContainerId: "gridCursos");
	grillaCursos.Bind(Model);
	grillaCursos.Pager(mode: WebGridPagerModes.All,
		firstText: "Primero", lastText: "Ultimo",
		previousText: "Anterior",
		nextText: "Siguiente",
		numericLinksCount: 15);

	if (grillaCursos.TotalRowCount == 0)
	{
		<section style="text-align:center; padding:20px">
			@ViewBag.Cursos_DefaultMessage
		</section>
	}
	else
	{
		@grillaCursos.GetHtml(htmlAttributes: new { id = "gridCursos" },
			tableStyle: "webgrid",
			headerStyle: "webgrid-header",
			footerStyle: "webgrid-footer",
			alternatingRowStyle: "webgrid-alternating-row",
			selectedRowStyle: "webgrid-selected-row",
			rowStyle: "webgrid-row-style",
			columns: grillaCursos.Columns(
						grillaCursos.Column(format: @<input type="hidden" class="idHidden" name="IDHidden" value="@item.id"/>),
						grillaCursos.Column(columnName: "institucion1.nombre", header: "Institución", style: "institucion"),
                        grillaCursos.Column(format: @<input type="hidden" class="idInstitucionCurso" name="idInstitucionCurso" value="@item.institucion1.id"/>),
						grillaCursos.Column(
							columnName: "ano",
							header: "Año",
							format: item => string.Concat(item.ano, item.division)
						),
						grillaCursos.Column(columnName: "nombre", header: "Nombre", style: "nombre"),
						grillaCursos.Column(format: @<div class="blob"><h2>Descripción</h2><p>@item.descripcion</p></div>)
			)
		)
	}
}      
<script type="text/javascript">
	var cursos = document.querySelectorAll('#gridCursos tbody > tr');
	$(cursos).hover(
			function () { $(this).find('.blob').css('display', 'block'); },
			function () { $(this).find('.blob').css('display', 'none'); }
    );
</script>